### PR TITLE
RRS-95 Landlord Profile Picture Upload

### PR DESCRIPTION
**Pull request by LukeHosk**
- Sets up supabase to store landlord profile pictures (RRS-54)
- Let's landlords add or change their profile picture on their profile page (RRS-56) 
  - Re-arranges landlord profile edititing to be done inline on profile page
- Shows the correct profile picture on the profile page (RRS-114)

also switched to Turbopack for dev mode to speed up testing

### CODE REVIEW

**Comment by LukeHosk** [comment]
@OttoChu, your star counting tests seem to be failing despite the right amount of stars being shown. Can you take a look.

**Comment by OttoChu** [comment]
It appears that it is pointing to the wrong div. I will change that for you

**Comment by OttoChu** [comment]
image


I don't know why I can't compile this branch. That is error I'm getting. On VScode, it is saying this:
image



I don't know what is happening. I am using pnpm and I can compile other branches fine.

**Comment by OttoChu** [comment]
I don't know what is happening but if I reset the database on a separate branch and go back to this branch, it will compile.

But then the profile page won't work. I assume you added a "landlord public profiles full" and it won't work unless I reset the database with this branch? Maybe?

**Comment by LukeHosk** [comment]
How odd, I'll have a look

**Comment by LukeHosk** [comment]
Seems to have been a weird Windows issue but https://github.com/CM20314-Group-7/rental-review/pull/111/commits/08eeae4485bb057a10345068eeefbc62d9a3648b this should fix it for you

**Comment by OttoChu** [comment]
image
Might want to fix that before merging

**Review by OttoChu — APPROVED** [review]

**Pull request merged**
