### PR TITLE
Remove extra on ToS

### PR DESCRIPTION
**Pull request by OttoChu**

### CODE REVIEW

**Comment by OttoChu** [comment]
@LukeHosk I don't know why the playwright test are not running...

**Comment by LukeHosk** [comment]
> @LukeHosk I don't know why the playwright test are not running...

#119 should fix this 🤞🏻

**Comment by OttoChu** [comment]
I just realised that the seed file is gone from merging your admin console branch and I can't find it

**Comment by OttoChu** [comment]
Never mind, found the file but I don't know how to make it to use the seed file in that folder when I reset the database

**Comment by LukeHosk** [comment]
> Never mind, found the file but I don't know how to make it to use the seed file in that folder when I reset the database 

Either:
- run the normal start command from inside the packages/supabase folder
- run pnpm start:supabase from the root

And it should start as normal

**Comment by LukeHosk** [comment]
Oh you were resetting not starting 

I don't believe I set up a command for that in the root yet, so either just do the normal command in the supabase package folder, or add one like I did for the other supabase commands in the package. JSONs and turbo.json

**Comment by OttoChu** [comment]
I figured it out, but then I don't know why the some tests are failing on my local machine but not on GitHub. 
image
All of the tests in the folders coloured in red just failed for some reason. 
image
That is the error for most of them

**Comment by LukeHosk** [comment]
Oh I remember getting that error but can't remember what caused it or how I fixed i

**Comment by OttoChu** [comment]
If it is fine on GitHub then I will ignore it. You can just merge this branch then

**Comment by LukeHosk** [comment]
Try 

`git clean -xdf && pnpm i && pnpm build`

To clear all the non-tracked files and then rebuild.

**Review by LukeHosk — APPROVED** [review]

**Pull request merged**
