### PR TITLE
RRS 35 & 145 link to claim property and display owning landlords in property page

### PR DESCRIPTION
**Pull request by OttoChu**
Just using Luke's code and added unit test to them

### CODE REVIEW

**Comment by OttoChu** [comment]
@LukeHosk I have no idea why the unit tests are not behaving. It works on my machine even after updating all modules and resetting the database. 

Screenshot 2024-03-11 151538
One of the failed test on here says that it is missing the 0s for the dates but the webpages definitely have dates in the format 01/01/2021. There is also another failed test saying it is getting 01/20/2021 but expecting 20/01/2024. There is no where in the code to get 01/20/2021. 

Can you have a look for me, please?

**Comment by LukeHosk** [comment]
> @LukeHosk I have no idea why the unit tests are not behaving. It works on my machine even after updating all modules and resetting the database.
> 
> Screenshot 2024-03-11 151538 One of the failed test on here says that it is missing the 0s for the dates but the webpages definitely have dates in the format 01/01/2021. There is also another failed test saying it is getting 01/20/2021 but expecting 20/01/2024. There is no where in the code to get 01/20/2021.
> Can you have a look for me, please?

looks to me like the site is serving the American date format in the workflow. I can have a look at how we fix that, or you cound make the test accept either format.

**Comment by LukeHosk** [comment]
@OttoChu I was expecting you would just make a regexp to match all date formats like this

```TypeScript
  const fuzzyMatchDate = (date: Date) => {
    const day = date.getDate().toString();
    const month = (date.getMonth() + 1).toString();
    const year = date.getFullYear().toString();
    const shortYear = year.slice(2, 4);

    // for each of day and month, if they are a single digit, allow a 0 at the front
    // allow day and month to be in either order
    // allow year to be in either format
    const fuzzyDateFormat = new RegExp(
      `(?:${ 
        day.length == 1 ? `0?${day}` : day
      }\/${
        month.length == 1 ? `0?${month}` : month
      }|${
        month.length == 1 ? `0?${month}` : month
      }\/${
        day.length == 1 ? `0?${day}` : day
      })\/(?:${year}|${shortYear})`
    )

    return fuzzyDateFormat;
  };

  const today = new Date();
  const todayMatcher = fuzzyMatchDate(today);

  console.log(todayMatcher.test('11/03/2024')); // true
  console.log(todayMatcher.test('11/3/2024')); // true
  console.log(todayMatcher.test('03/11/2024')); // true
  console.log(todayMatcher.test('3/11/2024')); // true
  console.log(todayMatcher.test('11/03/24')); // true
  console.log(todayMatcher.test('11/3/24')); // true
  console.log(todayMatcher.test('03/11/24')); // true
  console.log(todayMatcher.test('3/11/24')); // true
  
  console.log(todayMatcher.test('4/11/24')); // false
  ```

then you can just pass this expression to the matcher like [here in the docs](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-contain-text)

e.g.
```TypeScript
await expect(locator).toContainText( fuzzyMatchDate(today));
```
would then pass if any acceptable date is provided

**Comment by LukeHosk** [comment]
or we can [update the playwright config to use gb date format](https://playwright.dev/docs/emulation#locale--timezone)

**Comment by OttoChu** [comment]
This took longer than I thought it would be

**Review by LukeHosk — APPROVED** [review]

**Pull request merged**
