### PR TITLE
RRS-58 Add images to reviews

### PR DESCRIPTION
**Pull request by OttoChu**
Currently you can add pictures to a review but not see them yet.

All you can do right now is upload images. The rest will be in a separate pr. I just don't want to be so far behind development

### CODE REVIEW

**Comment by OttoChu** [comment]
@LukeHosk I don't know why the types are not passing again. I have the thing to change the encoding in my gitattribute. 

Also, I could not figure out why the delete function is not working. I have marked it with a TODO. Could you please have a look at it

**Comment by OttoChu** [comment]
Also ignore the history of this branch, GitHub doesn't like me

My email is getting spammed from this...

image

This is fun 😭

**Comment by LukeHosk** [comment]
> @LukeHosk I don't know why the types are not passing again. I have the thing to change the encoding in my gitattribute.
> 
> Also, I could not figure out why the delete function is not working. I have marked it with a TODO. Could you please have a look at it

I think your local supabase version is out of date

**Comment by OttoChu** [comment]
@LukeHosk I don't know if i have merged it properly or not because it won't compile after merging. It is saying that I am missing some modules.

image

I have ran pnpm i -f and it is still saying i am missing it.

**Comment by LukeHosk** [comment]
> @LukeHosk I don't know if i have merged it properly or not because it won't compile after merging. It is saying that I am missing some modules.
> 
> 
> 
> image
> 
> 
> 
> I have ran pnpm i -f and it is still saying i am missing it.

Yes you have merged wrong if you look at the changes files in the PR there's a lot which is just undoing recent changes. Including the package.json file that lists that module.

**Comment by LukeHosk** [comment]
@OttoChu have a look through the change list on GitHub, and make sure that everything in there is intentional.

Like I don't think you meant to change the test workflow script back to run on 'development'

**Review by LukeHosk — APPROVED** [review]

**Review by mattg42 — APPROVED** [review]

**Pull request merged**
