### PR TITLE
RRS-84 Users can view relevant reviews for a given landlord

### PR DESCRIPTION
**Pull request by OttoChu**
Added the reviews for a landlord to the profile
Added the unit test to test for the correct reviews

### CODE REVIEW

**Comment by OttoChu** [comment]
Sometimes an error pops up on the bottom left when you get to the page. It complains about hydration failed. I have no idea what that is supposed to mean. 
Even with that pop-up, everything on that page is fine and can be merged.

**Comment by LukeHosk** [comment]
I have had an in progress [PR for this](https://github.com/CM20254-Group-7/rental-review/pull/61) for several days.

Looks like you assigned the story to yourself not the task. I think we'll need to look at merging these 2 branches.

**Comment by LukeHosk** [comment]
> Sometimes an error pops up on the bottom left when you get to the page. It complains about hydration failed. I have no idea what that is supposed to mean. Even with that pop-up, everything on that page is fine and can be merged.

hydration errors are usually invalid HTML, list elements outside of a list, `<p>` inside a `<p>`, etc.

**Comment by OttoChu** [comment]
I have just looked at your pr and I think we have pretty much the same thing. I didn't realise there was a task that I missed.

I think once I get that hydration thing sorted then this can be merged unless you want to use your version instead.

**Comment by LukeHosk** [comment]
> I have just looked at your pr and I think we have pretty much the same thing. I didn't realise there was a task that I missed.

The idea is supposed to be that, the 'Task's are things for us to do/develop, and the 'Story's are things that the app should be able to do. Each stories generally has a list of 'blocked by' 'task's (though it looks like that was missed here).

I would avoid trying to work on any stories directly (unless it's making end-to-end tests for them), and instead work on the tasks that block them. I have my Jira set to show tasks only most of the time.

**Comment by LukeHosk** [comment]
> I think once I get that hydration thing sorted then this can be merged unless you want to use your version instead.

I think there's probably elements of both that we want to keep. e.g. I like that mine has the properties split into current and past, but you're displaying that list nicer

**Comment by LukeHosk** [comment]
It's actually kind of crazy how much of what we each did is very similar

Screenshot 2024-03-07 at 00 12 24
Screenshot 2024-03-07 at 00 14 50

**Comment by OttoChu** [comment]
They are almost the same. Do you want me to merge them together?

**Comment by LukeHosk** [comment]
merged layout with #61

**Pull request closed without merging**
