### PR TITLE
RRS-161 & RRS-167 & RRS-168 Landlord Registration Fix

### PR DESCRIPTION
**Pull request by LukeHosk**

### CODE REVIEW

**Review by OttoChu — CHANGES_REQUESTED** [review]
The form still requires the user to enter all fields even though some are marked as optional; otherwise, it will just return a failed message. 

Another thing to consider is not limiting the number of characters for the postcode to 7. They can be between 5 and 7, so we might want that instead.

**Comment by LukeHosk** [comment]
> The form still requires the user to enter all fields even though some are marked as optional; otherwise, it will just return a failed message.
> 
> Another thing to consider is not limiting the number of characters for the postcode to 7. They can be between 5 and 7, so we might want that instead.

None of the fields marked as optional are required (just checked)

will fix the postcode

**Comment by OttoChu** [comment]
Oh I meant this
image

It should not say optional here

**Comment by LukeHosk** [comment]
> Oh I meant this image
> 
> It should not say optional here

I will make those fields required then

**Comment by LukeHosk** [comment]
Screenshot 2024-03-20 at 12 15 24

Better?

**Review by OttoChu — APPROVED** [review]

**Pull request merged**
